* Week 2
** Greek Culture
   Geek has no history, it is all oral passdowns
   Geek history is around ~3000 to ~1100 did not exist. They did not call them selves Greek. We do not know that they are called. Since 1900 we have started calling them Minoans.
   Evans discovered the civilization found many records, all which were un readable to this day. 
   Minoans are very well known for their king Minos.
   They did well for themselves during the bronze age.
   Myceneans (Thats what we call them) probably called themselved Achaiol.
   They began priacy, the Myceneans took all Greek land and the lanf on the Minoans.
   A volcano namedThcara erupted subjected the Minoans to geographic problems, allowing the Myceneans to take them easily.
   Myceneans were led by war chief named Fanax (F on a \deg45)
   Michael Ventries knew the Myceneans lanuage (Linear B.) 
   Minoans were Linear A, which is unknown
   All sources indicate things went wrong for everyone (including the Myceneans) by a new maurauding group. 
   Pylos was burned to the ground, we know this because records were burned into clay.
   Only one civilization withstood the attacks, not defeating them, but a settle ment. The Egyptians called them the "Sea Peoples".
   The Sea Peoples made a mess of things
   By 1100 - 1000BCE Myceneans were decimated.
   This era is called the Mycenean Twillight
   These poeple had not interest in record keeping, for the next 250 years, there are no reccords.
   Then, around 700BCE we have a gerat find. A cup with NESTOPI written on it. \rightarrow NESTORS CUP
   This is a sign of literacy.
   A phonecian alphabet.
   8^th through 6^th centuries were spend becoming a Greek identity.
   Greeks find unity in culture, civilization and religion. Embodies in their Myths.
   Greece undertakes somewhat of a golden age.
   Defeat Persians (Classical Age, centered in Athens and Sparta)
   Athens and Sparta don't like eachother.
   Golden age gives way to Philip of Macedon and Alexander the Great.
   Philips was killed at one of his weddings, his son was left to lead.
   Alexander of Mastedon lead the Hellenistic period.
   From ~300 - *31* BCE when the Roman Period engulfs the last of the Greek empire

** Creation Myth
   We see the creation of the cosmos, maybe something more.
   Espabilishes something about a world Axis. 
   Everytime we organize a World Axis, we come closer to the divine. 
   Some cultures still belive this, Greek culture thought everything had divine relevance. 
   First type of creation myth \rightarrow nihilo (Out of nothing)
   A diety created the cosmos via word, thought, dream, or some kind of activity, but is a single entity who des it.
   Seccond type of creation myth \rightarrow Earth Diver
   The creator is less involved
   Sends some kind of being into the primordial state (water, etc) and this being starts the creation process
   This some kind of thing in the universe wherein the creator makes something strat the process.
   Third type \rightarrow Emergence type
   Science Fiction
   A being or beings come from other realms then reach the present one where in we dwell and they take their knowledge to create a new universe.
   Gradual Process
   Fourth Type \rightarrow Creation by disembodiement
   Creator being wh has a vast endless body.
   From this body, they remove pieces from themselves to create the universe
   It is all contained within them
   Fifth Type \rightarrow Creaking-Up
   There is an original Chaos, where in things start to emerge, but also start to breakup.
   Combining emergence with disembodiment
   Sometimes that breakup is active (use of sex act)
   Sometimes is it litteral and passive wherein the entity start dividing itself into pieces.
   Herold and his epic
   Most are a complete and fill rendition of the Greek creation story. 
   \frac{1}{2} of the real sources we have for myth
   Ordify Greek culture.
   Story as opposed to a synopsis
   Herold composedit - somewhere in the 8^th century wherein writing was first starting to get underway
   We don't know if he was litterate or an oral poet
   He is the first individual to emerge from Greek liturature.
   He names himself
   The theogony is a gold mine of mythological details of the generation of the Gods.
   Takes traditional tales that has been trasmitted orally from a variety of places.
   The Gods are chiefly Greek, however some of the story and prefix is actually fimilliar to the sonfs from the near East.
   2700 years later, it came down to us to determine it was an authoritative test.
   There are other theogonys we are told, with several differences, so we study the creation of the cosomos as Hesis saw it. 
   The first generation of Gods are rather abstract in their contempcies (the areas they has control)
   As we move to the Olympian Era, the Gods are most more speciailized.
   Moving from elemental to human depictions
   Gods become far more anthropomorphic
   The Gods in Hesis narrative have polyvalent (Many forms of reference)
   We have to understant the Gods are, and participate in the universe. 
   In the beginnning, according to Hesis, there was Chaos (In ancient Greek, litterally means a yawning, a gaping)
   The apcae wherein potential can be actuallized
   The implication is that it is something, but it is not something (Like zero)
   Chaos comes from the very Chano, I yawn.
   Hesis says that Chaos came first.
   Then, Gala (and other titans) emerge
   We do not know if they comes from chaos or if they simple emerge.
   Gala, or Ge, is the earth
   She is a pysical entity, as opposed to spacial.
   Then emerges Tartaros is the darkest, deepesst, part of the underworld.
   This titan is very comprehensable. Since we have a very specific idea of where the universe sits. He is not attached to Gala, but is the bottom half.
   Eros, emerges, the entitiy wherein the sexual impulse is experienced. 
   Primary deity, after Eros, sexual reproduction becomes the standard means
   Not sexual act, but the sexual impulse. 
   Nyx, is next to emerge, representing the night.
   Erebos, also emerges, representing darkness. 
   Not the darkness at 3am, more like going in the closet with the door shut and all night removed. It is complete darkness.
   Nyx and Erebos create Hemera and Aither (Day, and the brightness of day)
   This sexual act occurs in cycle, creating day and night to this day
   Gala created Ouranos above her, and Pontos below her. 
   Gala also produces monsters
   Group One \rightarrow Cyclopes, and Hekatoncheires.
   Cyclopse (Round eye, 1 enormous eye in their head.)
   Hekatoncheres (The hundread handed ones)
   These reprsents the preternatural (Beyond natural, do not occur in nature) They represent the potential forces in nature
   Lastly, Gigantes, a gitant. 
   These 3 monsters are not nessearly evil or bad, they are just obnormal.
   Now Gala mates with Ouranos (Earth and Sky) it becomes known as the Heros Hanos (The sacred marrage)
   They produce 12 children, the first generation of Anthrpormorphic Gods, *The titans*

** The Titans
   These entities are moving into a more anthroprmorhic shape. 
   This new generation is taking a more defined form. 
   Ouranos does not allow the children to be born, he physically pushes them back into Gala. (Burying them in the Earth)
   The new children represent a thread to Ouranos
   So Gala gives bith no another child, a keeps council with Kronos. 
   Kronos decides the only way to castrated with a sickle.
   This event itself creates a major flurrying of generation. The genetals of Ouranos falls into the Sea. 
   This creates the godess Aphrodite. 
   From the Greek work Aphros - Foam
   After the freeing of Gala children becomes the net order of priority, and they are.
   This caused a greakout of reproduction
   Kronos had second thoughts, with too may new people, he was loosing control
   The more entities out there, the more potential for his overthrow
   He threw the monsters, his biggest threats and put them in a cage with a dragon to guard. 
   Kronos takes his sister, laya, as his mate, and rule the civilization. 
   In acient Greek, Kronos means time. This act creates time as we know it (The big bang)
   Kronos has removed the undersirables. All is well.
   He belives his children may do to him as he did to his child.
   He devowered his children whole. 
   Kronos is just as bad as his father. His mother told him if he continues to act this way, he will be overthrown
   2 types of proficy (If then, which is avoidable, and just simply the poficy, unavoidable)
   Kronos continues to act this way, Kronos's wife then takes council of a last child. 
   This child is known today as Zeus. 
   He is hidden in a cave
   Amalthea and Melisa are Zeus' 2 adopted moms. (meaning the tender godess, a goat, Melisa is a bee.) This gives the 2 requirements milk and honey.
   Kronos vomits a stone he inhaled from his mother, causing all of his siblings to be vomited by his mother to aid him. They became known as the children on the titans, the Olympians.
   They come together and decide to fight their father Kronos. 
   Some of the remaining titans side with Kronos, others with the Olympians, starting the Titanomachy, the titan war.
   Metis and Prometheous are the only 2 to side with Zeus. 
   Zeus realizes he needs to bring in the monsters to aid him. 
   The olympians win, and the titans are cast into an eternal prison, Tartos.
   Atlas, a Titan, is now given the task of bracing the earth and sky. 
   Rehea opposes Zeus (without sucess)
   Now, Zeus is the king of the Gods and men. 
   He must now assess his rule to learn how to do it. 
   One of his several partners, is Metis who create a new child. He realizes the threat with this, and swallows Metis. 
   At this point Male dominence is established. 
   The giants decide to make a play for power, but Zeus defeat them as well. 
   3 fold fight, Kronos, Gala, and now the giants. 
   Zeus decides that he will power share with his brothers, but his word is final. Called the Tripartitc division. 
   His brother Haties controls all that is below, the underworld.
   Poseiden controls the earth and seas
   Zeus controls the top level, the sky
   Olympian theme, civilization over the natural world.

** People
   What about us?
   Our creation is the responsibility of the titan Prometheus. 
   The creator of human beings, the creator God and loves his beings. 
   A titanic offspring, who was more generous. 
   He has a twin browther named Epimetheous
   Prometheus as the titan who sided with Zeus, has special privledges. 
   His name means, he who thinks ahead. His brothers name meaning he who thinks after.
   He does not hold awe for Zeus because he thinks he will be overthrown at some point. 
   The brothers are given a gift, they travel to earth to "liven it up"
   They decide to create life on early.
   Prometheus creates the human figure, his brother creates the figure of beasts. 
   Prometheus creation is Man, male humans. 
   The Gods are very impressed and help him. Zeus is semi-concerned about this and being overthrown. 
   Zeus demands some kind of sacrifice to show humans fall below the Gods.
   Prometheus agrees this can be done.
   They meet at Mekone, a mythic place, an intersection of human and the divine. How man with worship Zeus will be determined here.
   Man slays a large Ox and divies it into piles. One pile was all the meat, and some fat. The other pile had bones and the fat.
   He decorated the bones and set the afire, and invited Zeus to eat the meat. Zeus chose the bones and the fat. 
   Clearly, Zeus chose the worse pile. Althrough God's dont need meat to survive, it is the lesser pile.
   Human beings now get the "good part" of the animal.
   This is also a rationalization myth, there is a recognition that life is monsterous. It survives by taking life.
   We are far removed from how this happens (How meat becomes food)
   Zeus is incadesent with rage, he was outrages he choose the worse pile, so he denied the secret of fire to man.
   We suffer because of the sin of our creator. 
   Prometheus went around the gods, and stole fire for man, giving man warm and the baility to cook meat. 
   He taught us things, the arts, think, wish, etc. 
   What Prometheus was commited in the eyes of the God is what is known as Hubris (Arrogance, defying the Olympian understanding of right)
   Zeus decided Prometheus has given too much to his creation and he must be punished. 
   Zeus canno't remove fire, so he decides to torture Prometheus by tying his to a rock in the middle of nowwhere.
   He has an Egael come and eat his liver every day. 


*** Def
   Type site, a name given for a culture which were spead all over a culture.
   Hellenic, Greek
   Hellenistic, Greek like
