#! /bin/sh

sxhkd &

# Auto Start
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Pictures/wallpaper/wallpaper.jpg 
xset r rate 225 30

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc monitor -d www Emacs 3 4 5 6 7 8 9 10

polybar main
