#+author: Anthony Tam, 1002583402
#+title: Essay Proposal
#+LATEX_HEADER:\usepackage[margin=0.75in]{geometry}
#+OPTIONS: toc:nil

For my essay assignment I will be writing about my theory of under what
circumstances hubris occurs, what the resulting punishment from the Gods will be.
I will also state if there are any specific patterns which follow from
similar acts of hubrus occurring. From my preliminary research, I will be
stating that there is a pattern between the act of hubris and the resulting
punishment from the Gods, a pattern can also be seen in repeated acts of
hubris. There are several examples we have already seen in lecture which
can support this thesis one example being the story at Mekone. The humans
were able to get away with giving Zeus a poor sacrifice, in turn they were
punished with the loss of fire. The correlation between this act of hubris
and punishment is that the humans kept the ox meat, but lost fire - their
only method of cooking the meat.\\

*Source One (Primary):*\\
Trzaskoma, Stephen, R. Scott Smith, Stephen Brunet, and Thomas G. Palaima.
Anthology of Classical Myth: Primary Sources in Translation. 1st ed.
Indianapolis, IN: Hackett Publishing Co., 2004. Print.\\ 

This source will be used for exact quotes from myths which demonstrate
hubris of both dialog and the setting of the event. The text may also be used
for images of artwork which may be related to the myth.\\

*Source Two (Secondary):*\\
Trzaskoma, Stephen, R. Scott Smith, Stephen Brunet, and Thomas G. Palaima.
Anthology of Classical Myth: Primary Sources in Translation. 1st ed.
Indianapolis, IN: Hackett Publishing Co., 2004. Print. \\

The same book also contains interpreted meanings of the myths. These notes
may aid in giving better clarification while reading the myth and also to give
important details.\\

*Source Three (Secondary):*\\
T, D. J. "Classic Mythology Lecture." Ontario, Mississauga. Lecture.\\

This source will be used for a better understanding of the myths in the
above book. The lectures notes are an interpreted of the myths, they
aid in a better understanding of the content as well as real world connections
to the myth.\\

*Source Three (Secondary):*\\
Powell, Barry B. Classical Myth. 8th ed. Boston: Pearson, 2015. Print.\\

This source offers a more in depth analysis of the myths learned in lecture. 
The analysis can be used to further explain my thesis and provide more concrete
examples to reinforce my ideas.\\\\

This list of courses will continue to expand over the series of the term and as more
topics are learned in class. More primary sources will also be added as the essay continues
to progress.
